### ISSUE TITLE
Multiple ember-ic-you in one template + action with an argument

### ISSUE THREAD

**Issue by manuel-reil** [Vestorly/ember-ic-you#1]
Hi,

having not tried it: 
1. Is it possible to include ember-ic-you multiple times in one template and component/controller?
2. Imagine a list of entries that are grouped by chapters. When scrolling to a chapter, a property should be updated by the current visible chapter. For that, the actions in ember-ic-you would be good to have arguments.

Or is there a better approach to this without ember-ic-you?

Thank you,
Manuel

**Comment by jondayton** [comment]
1. yes it will work right out of the box, because the event listeners are unique for each instance
2. currently the action just sends whether it's above or below the trigger line, but we could definitely add other data to it. what do you have in mind?
